# Generated by Django 5.0.2 on 2024-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('diet', models.CharField(max_length=50)),
                ('diseases', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
            ],
        ),
    ]
