# Generated by Django 5.0.1 on 2024-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_title", models.CharField(max_length=200)),
                ("party_message", models.TextField()),
                ("party_date", models.CharField(max_length=50)),
                ("party_time", models.CharField(max_length=50)),
                ("party_location", models.CharField(max_length=200)),
                ("optional_desserts", models.CharField(max_length=200)),
                ("gift_message", models.TextField()),
            ],
        ),
    ]
