# Generated by Django 5.0.1 on 2024-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_invitationdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationdetails",
            name="gift",
            field=models.BooleanField(default=False),
        ),
    ]
