# Generated by Django 5.0.1 on 2024-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_invitationdetails_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="InvitationDetails",
            new_name="InvitationDetail",
        ),
    ]
